################################# Default configuration ###################
# provide your domain here
baseURL = "https://help.bonfida.com/"
# theme
theme = "Dot"

# site title
title = "Bonfida Help Center"
# disable language
disableLanguages = ["fr"]
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#1d0da8"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/bonfidadotcom"


################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1


# banner
[Languages.en.params.banner]
title = "Support Center & Knowledge base"
subtitle = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Contact our 24/7 customer support line."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.en.menu.main]]
name = "orders"
url = "orders"
weight = 3

[[Languages.en.menu.main]]
name = "wallet"
url = "wallet"
weight = 4

[[Languages.en.menu.main]]
name = "contact"
url = "contact"
weight =5




################################### Franch Language ######################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2
copyright = "Copyright © 2020 un thème Hugo par [Gethugothemes](https://gethugothemes.com/)"

# banner
[Languages.fr.params.banner]
title = "Comment pouvons nous aider?"
subtitle = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
bg_image = "images/banner.jpg"
placeholder = "Avoir une question? Il suffit de demander ici ou de saisir les termes"

# call to action
[Languages.fr.params.cta]
enable = true
title = "Vous n'avez pas trouvé de réponse à votre question?"
content = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
# call to action button
[Languages.fr.params.cta.button]
enable = true
label = "Contactez nous"
link = "contact"


################## french navigation #################
[[Languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.fr.menu.main]]
name = "contact"
url = "contact"
weight = 3

# Dropdown menu
[[Languages.fr.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features"
  weight = 3
