################################# Default configuration ###################
# provide your domain here
baseURL = "https://help.bonfida.com/"
# theme
theme = "Dot"

# site title
title = "Bonfida帮助中心"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "/logo/logo-big.svg"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = "/logo/logo-big.svg"
# when logo is empty, it will shown your site title

# customize color
primary_color = "#1d0da8"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/bonfidadotcom"


################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1


# banner
[Languages.en.params.banner]
title = "帮助 & 知识中心"
subtitle = "向我们找寻您遇到问题的答案"
bg_image = "images/banner.jpg"
placeholder = "您有什么问题吗？请在这里询问"

# call to action
[Languages.en.params.cta]
enable = true
title = "没有找到您问题的答案吗？"
content = "请联系我们，我们24/7在线。"
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "联系我们"
link = "联系"


################## english navigation #################
[[Languages.en.menu.main]]
name = "主页"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "订单"
url = "orders"
weight = 2

[[Languages.en.menu.main]]
name = "钱包"
url = "wallet"
weight = 3

[[Languages.en.menu.main]]
name = "solible"
url = "solible"
weight =4

[[Languages.en.menu.main]]
name = "常见问题"
url = "faq"
weight = 5

[[Languages.en.menu.main]]
name = "联系我们"
url = "contact"
weight =6




################################### Chinese Language ######################
[Languages.zh]
languageName = "Zh"
languageCode = "zh-cn"
weight = 2
copyright = "Copyright © 2020 un thème Hugo par [Gethugothemes](https://gethugothemes.com/)"

# banner
[Languages.zh.params.banner]
title = "帮助 & 知识中心"
subtitle = "向我们找寻您遇到问题的答案"
bg_image = "images/banner.jpg"
placeholder = "您有什么问题吗？请在这里询问"

# call to action
[Languages.zh.params.cta]
enable = true
title = "没有找到您问题的答案吗？"
content = "请联系我们，我们24/7在线。"
# call to action button
[Languages.zh.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## french navigation #################
[[Languages.zh.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.zh.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.zh.menu.main]]
name = "contact"
url = "contact"
weight = 3

# Dropdown menu
[[Languages.zh.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.zh.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation"
  weight = 1

  [[Languages.zh.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing"
  weight = 2

  [[Languages.zh.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features"
  weight = 3
